# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_conversion_rate', models.IntegerField(default=0)),
                ('optimal_conversion_rate', models.IntegerField(default=0)),
                ('current_bounce_rate', models.IntegerField(default=0)),
                ('optimal_bounce_rate', models.IntegerField(default=0)),
                ('current_average_order_value', models.IntegerField(default=0)),
                ('optimal_average_order_value', models.IntegerField(default=0)),
                ('current_shopping_cart_abandonment_rate', models.IntegerField(default=0)),
                ('optimal_shopping_cart_abandonment_rate', models.IntegerField(default=0)),
                ('traffic_last_month', models.IntegerField(default=0)),
                ('traffic_this_month', models.IntegerField(default=0)),
                ('optimal_traffic', models.IntegerField(default=0)),
                ('revenue_last_month', models.IntegerField(default=0)),
                ('revenue_this_month', models.IntegerField(default=0)),
                ('optimal_revenue', models.IntegerField(default=0)),
                ('current_revenue_per_user', models.IntegerField(default=0)),
                ('optimal_revenue_per_user', models.IntegerField(default=0)),
            ],
        ),
    ]
