# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_auto_20170808_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Current_user_name',
            new_name='current_user_name',
        ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='current_user',
        #     field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
