# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0005_auto_20170808_0738'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='profile',
    #         name='current_user',
    #     ),
    # ]
#
