# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0006_remove_profile_current_user'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='profile',
    #         name='current_user_ref',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
    #     ),
    # ]
