# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0011_auto_20170808_0752'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='profile',
    #         old_name='current_user_ref',
    #         new_name='user_id',
    #     ),
    # ]
