# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0012_auto_20170808_0756'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='profile',
    #         name='user_id',
    #     ),
    # ]
