# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0007_auto_20170814_1541'),
        ('analytics', '0016_auto_20170809_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_guide_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskoftheday.Guide'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_step_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskoftheday.Step'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskoftheday.Task'),
        ),
    ]
