# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0017_auto_20170818_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_authcode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_guide_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='taskoftheday.Guide'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='taskoftheday.Step'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='taskoftheday.Task'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_user_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
