# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0022_remove_profile_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_rank',
            field=models.FloatField(default=0.0),
        ),
    ]
