# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0024_auto_20170926_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_rank',
            new_name='profilerank',
        ),
    ]
