# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0026_email_subsciption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_subsciption',
            name='unsubcription_reason',
        ),
    ]
