# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0028_email_subsciption_unsubcription_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email_subsciption',
            new_name='Email_Subscription',
        ),
    ]
