# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0029_auto_20170928_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_subscription',
            name='subcription_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
