# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0031_auto_20170928_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_subscription',
            name='unsubcription_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
