# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('referrals', '0001_initial'),
        ('analytics', '0033_delete_email_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='referrals.Referral'),
        ),
    ]
