# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0034_profile_referral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-profilerank',), 'verbose_name': 'Profile'},
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
