# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0036_auto_20171004_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
