# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0039_profile_http_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='http_auth',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
