# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0041_auto_20171010_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='http_auth',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
