# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 08:58
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0042_auto_20171010_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='http_auth',
            field=jsonfield.fields.JSONField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
