# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 09:05
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0043_auto_20171010_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='http_auth',
            field=annoying.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
