# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0044_auto_20171010_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='http_auth',
        ),
    ]
