# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0045_remove_profile_http_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_user_name',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
