# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sb_shortlink', '0004_auto_20171012_1424'),
        ('analytics', '0046_auto_20171011_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilelink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='sb_shortlink.shortlink'),
        ),
    ]
