# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0047_profile_profilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='revoke_uri',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_expiry',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_uri',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
