# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 10:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0048_auto_20171026_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
