# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0049_profile_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='json',
            new_name='flow',
        ),
    ]
