# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:19
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0051_auto_20171128_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flow1',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
