# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0052_auto_20171128_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flow1',
        ),
        migrations.AddField(
            model_name='profile',
            name='accountid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
