# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0053_auto_20171129_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
