# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0054_auto_20171129_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
