# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
