# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sb_shortlink', '0002_auto_20171012_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='user_id',
            new_name='user',
        ),
    ]
