# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sb_shortlink', '0003_auto_20171012_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
    ]
