# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sb_mail_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('server', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('auth_type', models.CharField(choices=[('SSL', 'SSL'), ('TSL', 'TSL'), ('TTL', 'TTL')], max_length=5)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=5)),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed')], max_length=10)),
                ('server_type', models.CharField(choices=[('POP', 'POP'), ('IMAP', 'IMAP')], max_length=10)),
                ('priority', models.CharField(max_length=5)),
                ('keep_attachment', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='sbmail_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('to_email', models.CharField(max_length=50)),
                ('from_email', models.CharField(max_length=5)),
                ('cc_email', models.CharField(max_length=30)),
                ('bbc_email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=5)),
                ('body_text', models.CharField(max_length=5)),
                ('body_html', models.CharField(max_length=5)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Html', 'Html')], max_length=10)),
                ('object', models.CharField(max_length=5)),
                ('object_id', models.CharField(max_length=5)),
            ],
        ),
    ]
