# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sb_mail_server',
            name='keep_attachment',
            field=models.FileField(upload_to='files'),
        ),
    ]
