# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0002_auto_20170928_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sb_mail_server',
            options={'verbose_name': 'Mail Server', 'verbose_name_plural': 'Mail Servers'},
        ),
        migrations.AlterModelOptions(
            name='sbmail_template',
            options={'verbose_name': 'Mail Template', 'verbose_name_plural': 'Mail Templates'},
        ),
    ]
