# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0003_auto_20170928_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sb_mail_server',
            name='auth_type',
            field=models.CharField(choices=[('SSL', 'SSL'), ('TSL', 'TSL'), ('TTL', 'TTL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='keep_attachment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='server',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='server_type',
            field=models.CharField(choices=[('POP', 'POP'), ('IMAP', 'IMAP'), ('SMTP', 'SMTP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='type',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='bbc_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='body_html',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='body_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='cc_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='from_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='to_email',
            field=models.CharField(max_length=100),
        ),
    ]
