# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0004_auto_20170928_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('subcription_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('unsubcription_datetime', models.DateTimeField(null=True)),
                ('unsubcription_reason', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscription',
            },
        ),
    ]
