# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0006_auto_20170928_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmail_template',
            name='mailserver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='sb_mail.sb_mail_server'),
        ),
    ]
