# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0007_sbmail_template_mailserver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbmail_template',
            name='object_id',
        ),
        migrations.AddField(
            model_name='sbmail_template',
            name='object_package',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('Html', 'HTML')], max_length=10),
        ),
    ]
