# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0008_auto_20170928_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_sb_mail_server',
            fields=[
                ('sb_mail_server_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='sb_mail.sb_mail_server')),
                ('sb', models.CharField(max_length=90)),
            ],
            bases=('sb_mail.sb_mail_server',),
        ),
        migrations.AlterField(
            model_name='email_subscription',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='email_subscription',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='email_subscription',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='email_subscription',
            name='subcription_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Subscription Time'),
        ),
        migrations.AlterField(
            model_name='email_subscription',
            name='unsubcription_datetime',
            field=models.DateTimeField(null=True, verbose_name='Unsubscription Time'),
        ),
        migrations.AlterField(
            model_name='email_subscription',
            name='unsubcription_reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unsubscription Reason'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='bbc_email',
            field=models.CharField(max_length=100, verbose_name='BBC Email'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='body_html',
            field=models.TextField(max_length=500, verbose_name='Body Html'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='body_text',
            field=models.TextField(max_length=500, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='cc_email',
            field=models.CharField(max_length=100, verbose_name='CC Email'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='from_email',
            field=models.CharField(max_length=100, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='mailserver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='sb_mail.sb_mail_server', verbose_name='Mail Server ID'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='object',
            field=models.CharField(max_length=90, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='object_package',
            field=models.CharField(max_length=90, verbose_name='Object Package'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='to_email',
            field=models.CharField(max_length=100, verbose_name='To Email'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('Html', 'HTML')], max_length=10, verbose_name='Type'),
        ),
    ]
