# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0009_auto_20170929_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_sb_mail_server',
            name='sb_mail_server_ptr',
        ),
        migrations.DeleteModel(
            name='in_sb_mail_server',
        ),
    ]
