# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0010_auto_20170929_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('to_email', models.CharField(max_length=100, verbose_name='To Email')),
                ('from_email', models.CharField(max_length=100, verbose_name='From Email')),
                ('cc_email', models.CharField(max_length=100, verbose_name='CC Email')),
                ('bbc_email', models.CharField(max_length=100, verbose_name='BBC Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('body_text', models.TextField(max_length=500, verbose_name='Body Text')),
                ('body_html', models.TextField(max_length=500, verbose_name='Body Html')),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=10, verbose_name='Type')),
                ('object_package', models.CharField(max_length=90, verbose_name='Object Package')),
                ('object', models.CharField(max_length=90, verbose_name='Object')),
                ('object_id', models.CharField(max_length=90, verbose_name='Object ID')),
                ('status',
                 models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Queue', 'Queue')], max_length=10,
                                  verbose_name='Status')),
                ('priority',
                 models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=10,
                                  verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Mail Message',
                'verbose_name_plural': 'Mail Message',
            },
        ),
        migrations.CreateModel(
            name='mail_server',
            fields=[
            ],
            options={
                'verbose_name': 'Out Mail Servers',
                'proxy': True,
                'indexes': [],
            },
            bases=('sb_mail.sb_mail_server',),
        ),
        migrations.AlterModelOptions(
            name='sb_mail_server',
            options={'verbose_name': 'In Mail Server', 'verbose_name_plural': 'In Mail Servers'},
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='auth_type',
            field=models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS    '), ('TTL', 'TTL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='type',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='mail_message',
            name='mailserver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='sb_mail.sb_mail_server', verbose_name='Mail Server ID'),
        ),
    ]
