# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0011_auto_20170929_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_message',
            name='bbc_email',
            field=models.CharField(max_length=100, null=True, verbose_name='BBC Email'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='body_html',
            field=models.TextField(max_length=500, null=True, verbose_name='Body Html'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='body_text',
            field=models.TextField(max_length=500, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='cc_email',
            field=models.CharField(max_length=100, null=True, verbose_name='CC Email'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='from_email',
            field=models.CharField(max_length=100, null=True, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='object',
            field=models.CharField(max_length=90, null=True, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='object_id',
            field=models.CharField(max_length=90, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='object_package',
            field=models.CharField(max_length=90, null=True, verbose_name='Object Package'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=10,
                                   null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Queue', 'Queue')], max_length=10,
                                   null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='to_email',
            field=models.CharField(max_length=100, null=True, verbose_name='To Email'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='type',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=10, null=True,
                                   verbose_name='Type'),
        ),
    ]
