# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0012_auto_20170929_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_message_attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, null=True, verbose_name='Title')),
                ('file', models.FileField(null=True, upload_to='files', verbose_name='File')),
                ('time', models.DateTimeField(null=True, verbose_name='Attachment Time')),
                ('mail_message_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sb_mail.mail_message',
                                   verbose_name='Mail Message ID')),
            ],
            options={
                'verbose_name': 'Mail Message Attachment',
                'verbose_name_plural': 'Mail Message Attachment',
            },
        ),
    ]
