# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0015_mail_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail_message',
            name='name',
        ),
    ]
