# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0016_remove_mail_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sb_mail_server',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sb_mail_server',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
