# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0017_auto_20171002_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_subscription',
            name='unsubcription_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unsubscription Time'),
        ),
    ]
