# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0019_auto_20171003_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sb_mail_server',
            name='priority',
            field=models.IntegerField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
