# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0027_sb_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sb_settings',
            name='support_email',
            field=models.EmailField(default='a@gmail.com', max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
