# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0028_sb_settings_support_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sb_settings',
            options={'ordering': ('id',), 'verbose_name': 'Group Settings'},
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='body_html',
            field=models.TextField(max_length=2000, verbose_name='Body Html'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='body_text',
            field=models.TextField(max_length=2000, verbose_name='Body Text'),
        ),
    ]
