# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0030_sb_settings_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_message',
            name='text_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Html', 'HTML')], max_length=10, null=True,
                                   verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='body_html',
            field=models.TextField(max_length=2000, null=True, verbose_name='Body Html'),
        ),
        migrations.AlterField(
            model_name='mail_message',
            name='body_text',
            field=models.TextField(max_length=2000, null=True, verbose_name='Body Text'),
        ),
    ]
