# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sb_mail', '0031_auto_20171005_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_message',
            name='text_type',
            field=models.CharField(choices=[('plain', 'plain'), ('Html', 'HTML')], max_length=10, null=True,
                                   verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='sbmail_template',
            name='type',
            field=models.CharField(choices=[('plain', 'plain'), ('Html', 'HTML')], max_length=10, verbose_name='Type'),
        ),
    ]
