# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('guide', 'sequence_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('step', 'sequence_number')]),
        ),
    ]
