# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0004_auto_20170814_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_img',
            field=models.ImageField(upload_to='static/taskoftheday/img/uploads-tasks'),
        ),
    ]
