# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskoftheday', '0007_auto_20170814_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_datetime', models.DateTimeField()),
                ('guide_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskoftheday.Guide')),
                ('step_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskoftheday.Step')),
                ('task_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskoftheday.Task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
