# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0008_usertaskhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaskhistory',
            old_name='complete_datetime',
            new_name='completion_datetime',
        ),
    ]
