# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0011_usertasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userTasks',
            new_name='UserTask',
        ),
    ]
