# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0013_auto_20171013_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='current_task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
