# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0016_auto_20171013_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.AddField(
            model_name='usertaskhistory',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
