# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0017_auto_20171014_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/taskoftheday/img/uploads-tasks'),
        ),
    ]
