# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskoftheday', '0018_auto_20171027_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_img',
            field=models.ImageField(blank=True, default=1, upload_to='static/taskoftheday/img/uploads-tasks'),
            preserve_default=False,
        ),
    ]
